import { Provider } from "react-redux";
import { RouterProvider, createBrowserRouter } from "react-router-dom";
import Cookies from "universal-cookie";
import Login from "../pages/Login/Login";
import Register from "../pages/Register/Register";
import ForgotPassword from "../pages/ForgotPassword/ForgotPassword";
import UpdatePassword from "../pages/ForgotPassword/UpdatePassword";
import ProtectedRoute from "../utils/PrivateRoute";
import Home from "../pages/Home/Home";
import CompanyLanding from "../pages/Organizations/OrganizationLanding";
import Companies from "../pages/Organizations/Organization";
import CompanyView from "../pages/CompanyView/CompanyView";
import CompanyOverview from "../pages/CompanyView/CompanyOverview";
import JobPostView from "../pages/jobView/JobPostView";
import Jobs from "../pages/Jobs/Jobs";
import { Profile } from "../pages/Profile/Profile";
import ProfilePerformance from "../pages/ProfilePerformance/ProfilePerformance";
import ProfileSetting from "../pages/ProfileSettings/ProfileSetting";
import JobVacancy_Company from "../pages/specificCompanyVacancy/Specific_CompanyJobVacancy";
import { store } from "./store";
